version: '3.9'

configs:
  server-env:
    file: .env

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
